<?php require "templates/header.phtml"?>
<?php require "templates/form.estaciones.phtml"?>


<div class="container text-center">
  <div class="row align-items-start">
  <?php foreach($estaciones as $estacion): ?>
    <div class="col">
    <a><?= $estacion->nombre_estacion ?> </a>

    <div class="actions mt-2">
            <a href="eliminar/<?= $estacion->id_estacion?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
        </div>
        <?php if(!$estacion->finalizo_estacion): ?> 
                <a href="finalizar/<?= $estacion->id_estacion ?>" type="button" class='btn btn-success ml-auto'>Finalizar</a> 
            <?php endif ?>



    </div>

  <?php endforeach ?>

  </div>
</div>
  


<?php  require "templates/footer.phtml"; 