<?php require "templates/header.phtml"?>
<?php require "templates/form.ciudades.phtml"?>


<div class="container text-center">
  <div class="row align-items-start">
  <?php foreach($ciudades as $ciudad): ?>
    <div class="col">
    <a><?= $ciudad->nombre?>(<?=$ciudad->id_estacion?>)</a>

    <div class="actions mt-2">
            <a href="infoCiudad/<?= $ciudad->id_ciudad?>" type="button" class='btn btn-danger ml-auto'>Ver mas Info</a>
            <a href="eliminarCiudad/<?= $ciudad->id_ciudad?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
            <a href="editar/" type="button" class='btn btn-secondary ml-auto mt-2'>Editar</a>
        </div>
    </div>

  <?php endforeach ?>

  </div>
</div>
  


<?php  require "templates/footer.phtml"; 